# Generated by Django 4.1 on 2023-07-02 10:19

from django.db import migrations

from ..migration_data import tags


def create_tags(apps, schema_editor):
    Tag = apps.get_model('core', 'Tag')
    for i in tags:
        Tag.objects.create(title=i)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_tags)]
