# Generated by Django 4.1 on 2023-07-02 10:31

from django.db import migrations


def create_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for i in range(10):
        User.objects.create(username=f'user{i}', password=f'qwerty{i}')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20230702_1419"),
    ]

    operations = [migrations.RunPython(create_users)]
