# Generated by Django 4.1 on 2023-07-02 10:37

from django.db import migrations


def create_blogs(apps, schema_editor):
    Blog = apps.get_model('core', 'Blog')
    User = apps.get_model('core', 'User')
    for i in range(5):
        Blog.objects.create(title=f'blog{i}', description=f'qwerty{i}', owner=User.objects.get(pk=i+1))
    blog0 = Blog.objects.get(pk=1)
    blog0.authors.add(User.objects.get(pk=2))
    blog0.authors.add(User.objects.get(pk=3))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20230702_1431"),
    ]

    operations = [migrations.RunPython(create_blogs)]
