# Generated by Django 4.1 on 2023-07-02 10:57

from django.db import migrations


def create_posts(apps, schema_editor):
    Post = apps.get_model('core', 'Post')
    Tag = apps.get_model('core', 'Tag')
    Blog = apps.get_model('core', 'Blog')
    User = apps.get_model('core', 'User')
    for i in range(5):
        Post.objects.create(title=f'post{i}', body=f'some body', author=User.objects.get(pk=i+1),
                            blog=Blog.objects.get(pk=i+1))
    post0 = Post.objects.get(pk=1)
    post0.tags.add(Tag.objects.get(pk=1))
    post0.tags.add(Tag.objects.get(pk=2))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20230702_1437"),
    ]

    operations = [migrations.RunPython(create_posts)]
